#-------------------------------
# General Site Settings
title: Sanara
logo: # You can add own logo. For example '/images/logo.png'.
description: Hi, my name is Nick Adams. I’m a Product Designer and Photographer based in NY. I like being at the center of events, being free and enjoying every moment.
baseurl: "" # The subpath of your site, e.g. /blog
url: "https://sanara.netlify.app/" # The base hostname & protocol for your site, e.g. http://example.com


#-------------------------------
# Author Settings
author-name: Nick Adams

#-------------------------------
# Hero Settings
hero:
  image: '/images/70.jpg'
  title: Nick Adams
  description: Thoughts, stories and ideas.

social:
- {icon: "ion-logo-twitter", link: "https://twitter.com"}
- {icon: "ion-logo-facebook", link: "https://facebook.com"}
- {icon: "ion-logo-dribbble", link: "https://dribbble.com"}
- {icon: "ion-logo-instagram", link: "https://instagram.com"}
- {icon: "ion-logo-github", link: "https://github.com"}
- {icon: "ion-logo-vimeo", link: "https://vimeo.com/"}

# Example of adding a new link to the author section and footer - {icon: "ion-logo-pinterest", link: "https://pinterest.com"}
# Other icons can be found at https://ionicons.com/v4/


#-------------------------------
# Contact Settings
contact:
  email: your@email.com # Add your email for contact form
  description: Sanara comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want. # Add a description of your form

# NOTE
# Sanara comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: anvodstudio-demo # Add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: true # To enable the mailchimp form, use the value 'true'. To disable the form, use the value 'false' or leave the field blank.
mailchimp-title: Get Interesting News # Add your title.
mailchimp-text: Subscribe to our newsletter and we’ll send you the emails of latest posts. # Add your description.
mailchimp-identifier: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e


#-------------------------------
# Build settings
markdown: kramdown
permalink: /:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

paginate: 9
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  /:title

sass:
  sass_dir: _sass
  style: compressed